Fixes for sign-compare warnings due to signedness of size_t
Reported by AmR|EiSa

src/common/pecoff/pecoffutils.cc:315:25: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   for (int idx = 0; idx < kMDGUIDSize; ++idx) {
                         ^
src/common/pecoff/pecoffutils.cc:358:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   for (int i = 0; i < debug_directory_size/sizeof(PeDebugDirectory); i++) {
                     ^
src/common/pecoff/pecoffutils.cc:457:27: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (data_directory_size < entry)